version: '3'
services:
  #### logstash
  logstash:
    container_name: logstash
    build:
      context: builder/
      args:
        ELASTIC_VERSION: ${LOGSTASH_VERSION}
    #volumes:
      #- ./config:/usr/share/logstash/config:ro,Z
      #- ./pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
